package com.infotech.adb.enums;

public enum PrintReportEnums {
    GD_REPORT,
    FT_REPORT,
    BCA_REPORT,
    FT_IMPORT_REPORT,
    BDA_REPORT,
    ITRS_RPEORT,
    BCA_REALIZED_REPORT,
    EXPORT_OVERDUE_REPORT,
    FI_REGISTER_REPORT,
    BDA_REGISTER_REPORT,
    SHIPPED_STATUS_REPORT,
    SETTLEMENT_OF_FI_PRINT,
    SETTLEMENT_OF_FI_REPORT,
    GD_IMPORT_REPORT,

}
